--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
- !ruby/struct:SM::Flow::P 
  body: get the configuration of the node get_configuration(configuration=nil)
- !ruby/object:SM::Flow::LIST 
  contents: 
  - !ruby/struct:SM::Flow::LI 
    label: "configuration:"
    body: "[Jabber::XData]"
  type: :NOTE
full_name: Jabber::PubSub::NodeHelper#get_configuration
is_singleton: false
name: get_configuration
params: (subid = nil)
visibility: public
