--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Jabber::MUC::MUCClient#get_room_configuration
is_singleton: false
name: get_room_configuration
params: ()
visibility: public
