--- !ruby/object:RI::MethodDescription 
aliases: []

block_params: 
comment: 
full_name: Jabber::MUC::MUCClient#submit_room_configuration
is_singleton: false
name: submit_room_configuration
params: (options)
visibility: public
