--- !ruby/object:RI::ClassDescription 
attributes: []

class_methods: 
- !ruby/object:RI::MethodSummary 
  name: new
comment: 
- !ruby/struct:SM::Flow::P 
  body: SubscriptionConfig
- !ruby/struct:SM::Flow::P 
  body: An &lt;options&gt; XMPP element, see example 57 in http://www.xmpp.org/extensions/xep-0060.html#subscriber-configure-success
constants: []

full_name: Jabber::PubSub::SubscriptionConfig
includes: []

instance_methods: 
- !ruby/object:RI::MethodSummary 
  name: jid
- !ruby/object:RI::MethodSummary 
  name: jid=
- !ruby/object:RI::MethodSummary 
  name: subid
- !ruby/object:RI::MethodSummary 
  name: subid=
name: SubscriptionConfig
superclass: Configuration
